version: 2

project_name: mcp-scaleway-functions

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/mcp-scaleway-functions
    ldflags:
      - -s -w -X {{ .ModulePath }}/internal/constants.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin

kos:
  - repositories: [cyclimse/mcp-scaleway-functions]
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    labels:
      io.modelcontextprotocol.server.name: "io.github.cyclimse/mcp-scaleway-functions"

mcp:
  name: io.github.cyclimse/mcp-scaleway-functions
  title: "MCP Scaleway Functions"
  description: "Unofficial MCP Server for Scaleway Serverless Functions"

  auth:
    type: none

  repository:
    source: github
    url: https://github.com/cyclimse/mcp-scaleway-functions
    id: "1061220206"

  packages:
    - registry_type: oci
      identifier: "docker.io/cyclimse/mcp-scaleway-functions:{{ .Version }}"
      transport:
        type: stdio

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
